
import java.awt.Graphics;
import ScenarioUI.ScenarioUI;
import Usecase.UsecaseUI;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;

public class UCDevUI extends javax.swing.JFrame {

    /**
     * Creates new form UCDevUI
     */
    public UCDevUI() {
        initComponents();
        UCnametxt.setVisible(false);
        AssoIDtxt.setVisible(false);
        AssoNametxt.setVisible(false);
        DepenIDtxt.setVisible(false);
        DepenNametxt.setVisible(false);
        GeneralIDtxt.setVisible(false);
        GeneralNametxt.setVisible(false);
        id.setVisible(false);
        name.setVisible(false);
        Description.setVisible(false);
        actorIDtxt.setVisible(false);
        actorNametxt.setVisible(false);
        Descriptiontxt.setVisible(false);
        addActorBtn.setVisible(false);
        addUsecaseBtn.setVisible(false);
        sterio.setVisible(false);
        sterioComboBox.setVisible(false);
        usecaseIDtxt.setVisible(false);
        
    }

    public void drawPaint(Graphics g){
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawOval(20, 20, 60, 60);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jToolBar1 = new javax.swing.JToolBar();
        Diagram = new javax.swing.JLabel();
        systemBtn = new javax.swing.JButton();
        actorBtn = new javax.swing.JButton();
        usecaseBtn = new javax.swing.JButton();
        associationBtn = new javax.swing.JButton();
        generalBtn = new javax.swing.JButton();
        dependencyBtn = new javax.swing.JButton();
        SplitPane = new javax.swing.JSplitPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        actorIDtxt = new javax.swing.JTextField();
        actorNametxt = new javax.swing.JTextField();
        UCnametxt = new javax.swing.JTextField();
        AssoIDtxt = new javax.swing.JTextField();
        AssoNametxt = new javax.swing.JTextField();
        GeneralIDtxt = new javax.swing.JTextField();
        GeneralNametxt = new javax.swing.JTextField();
        DepenIDtxt = new javax.swing.JTextField();
        DepenNametxt = new javax.swing.JTextField();
        Description = new javax.swing.JLabel();
        Descriptiontxt = new javax.swing.JTextField();
        addActorBtn = new javax.swing.JButton();
        addUsecaseBtn = new javax.swing.JButton();
        sterio = new javax.swing.JLabel();
        sterioComboBox = new javax.swing.JComboBox<>();
        usecaseIDtxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        ScenarioView = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UCDev");

        jSplitPane2.setDividerLocation(100);

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        Diagram.setText("Diagram");
        jToolBar1.add(Diagram);

        systemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Object.gif"))); // NOI18N
        systemBtn.setText("System");
        systemBtn.setFocusable(false);
        systemBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        systemBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(systemBtn);

        actorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actor.gif"))); // NOI18N
        actorBtn.setText("Actor");
        actorBtn.setFocusable(false);
        actorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actorBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        actorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actorBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(actorBtn);

        usecaseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UseCase.gif"))); // NOI18N
        usecaseBtn.setText("Use case");
        usecaseBtn.setFocusable(false);
        usecaseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usecaseBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        usecaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usecaseBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(usecaseBtn);

        associationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Association.gif"))); // NOI18N
        associationBtn.setText("Association");
        associationBtn.setFocusable(false);
        associationBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        associationBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        associationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(associationBtn);

        generalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UniAssociation.gif"))); // NOI18N
        generalBtn.setText("Generalization");
        generalBtn.setFocusable(false);
        generalBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        generalBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        generalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(generalBtn);

        dependencyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DependencyRight.gif"))); // NOI18N
        dependencyBtn.setText("Include/Extends");
        dependencyBtn.setFocusable(false);
        dependencyBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dependencyBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dependencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dependencyBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(dependencyBtn);

        jSplitPane2.setLeftComponent(jToolBar1);

        SplitPane.setBackground(new java.awt.Color(255, 255, 255));
        SplitPane.setDividerLocation(400);
        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel3.setText("ID");
        SplitPane.setRightComponent(jLabel3);

        jPanel2.setLayout(null);

        id.setText("Use case ID");
        jPanel2.add(id);
        id.setBounds(10, 14, 70, 14);

        name.setText("Use case Name");
        jPanel2.add(name);
        name.setBounds(10, 40, 90, 14);
        jPanel2.add(actorIDtxt);
        actorIDtxt.setBounds(90, 10, 103, 30);
        jPanel2.add(actorNametxt);
        actorNametxt.setBounds(100, 40, 103, 30);
        jPanel2.add(UCnametxt);
        UCnametxt.setBounds(100, 40, 220, 30);
        jPanel2.add(AssoIDtxt);
        AssoIDtxt.setBounds(90, 10, 100, 30);
        jPanel2.add(AssoNametxt);
        AssoNametxt.setBounds(90, 40, 160, 30);
        jPanel2.add(GeneralIDtxt);
        GeneralIDtxt.setBounds(90, 10, 100, 30);
        jPanel2.add(GeneralNametxt);
        GeneralNametxt.setBounds(90, 40, 220, 30);
        jPanel2.add(DepenIDtxt);
        DepenIDtxt.setBounds(90, 10, 100, 30);
        jPanel2.add(DepenNametxt);
        DepenNametxt.setBounds(90, 40, 220, 30);

        Description.setText("Description");
        jPanel2.add(Description);
        Description.setBounds(330, 10, 70, 20);
        jPanel2.add(Descriptiontxt);
        Descriptiontxt.setBounds(410, 10, 220, 30);

        addActorBtn.setText("Save Actor");
        jPanel2.add(addActorBtn);
        addActorBtn.setBounds(540, 40, 90, 30);

        addUsecaseBtn.setText("Properties");
        addUsecaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsecaseBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addUsecaseBtn);
        addUsecaseBtn.setBounds(510, 40, 130, 30);

        sterio.setText("Stereotype");
        jPanel2.add(sterio);
        sterio.setBounds(330, 50, 60, 14);

        sterioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Person", "System" }));
        jPanel2.add(sterioComboBox);
        sterioComboBox.setBounds(410, 40, 90, 30);
        jPanel2.add(usecaseIDtxt);
        usecaseIDtxt.setBounds(90, 10, 120, 30);

        SplitPane.setRightComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        SplitPane.setLeftComponent(jPanel1);

        jSplitPane2.setRightComponent(SplitPane);
        SplitPane.getAccessibleContext().setAccessibleName("");

        jScrollPane1.setViewportView(jSplitPane2);

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("New");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Save as");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Import XMI");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Export XMI");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        View.setText("View");

        ScenarioView.setText("Scenario");
        ScenarioView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScenarioViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ScenarioViewMousePressed(evt);
            }
        });
        View.add(ScenarioView);

        jMenuBar1.add(View);

        jMenu3.setText("About");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actorBtnActionPerformed
        actorNametxt.setVisible(true);
        UCnametxt.setVisible(false);
        id.setVisible(true);
        actorIDtxt.setVisible(true);
        AssoIDtxt.setVisible(false);
        AssoNametxt.setVisible(false);
        DepenIDtxt.setVisible(false);
        DepenNametxt.setVisible(false);
        GeneralIDtxt.setVisible(false);
        GeneralNametxt.setVisible(false);
        name.setVisible(true); 
        Description.setVisible(true);
        Descriptiontxt.setVisible(true);
        addActorBtn.setVisible(true);
        sterio.setVisible(true);
        sterioComboBox.setVisible(true);
        addUsecaseBtn.setVisible(false);
        usecaseIDtxt.setVisible(false);
        
        SMCanvas sm = new SMCanvas();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(sm, BorderLayout.NORTH);

        
    }//GEN-LAST:event_actorBtnActionPerformed

    private void usecaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usecaseBtnActionPerformed
        actorIDtxt.setVisible(false);
        actorNametxt.setVisible(false);
        UCnametxt.setVisible(true);
        id.setVisible(true);
        AssoIDtxt.setVisible(false);
        AssoNametxt.setVisible(false);
        DepenIDtxt.setVisible(false);
        DepenNametxt.setVisible(false);
        GeneralIDtxt.setVisible(false);
        GeneralNametxt.setVisible(false);
        name.setVisible(true); 
        Description.setVisible(false);
        Descriptiontxt.setVisible(false);
        addActorBtn.setVisible(false);
        sterio.setVisible(false);
        sterioComboBox.setVisible(false);
        addUsecaseBtn.setVisible(true);
        usecaseIDtxt.setVisible(true);
    }//GEN-LAST:event_usecaseBtnActionPerformed

    private void associationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationBtnActionPerformed
        /*actorNametxt.setVisible(false);
        UCnametxt.setVisible(false);
        id.setVisible(true);
        actorIDtxt.setVisible(true);
        AssoIDtxt.setVisible(true);
        AssoNametxt.setVisible(true);
        DepenIDtxt.setVisible(false);
        DepenNametxt.setVisible(false);
        GeneralIDtxt.setVisible(false);
        GeneralNametxt.setVisible(false);*/
    }//GEN-LAST:event_associationBtnActionPerformed

    private void generalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalBtnActionPerformed
        /*actorNametxt.setVisible(false);
        UCnametxt.setVisible(false);
        id.setVisible(true);
        actorIDtxt.setVisible(true);
        AssoIDtxt.setVisible(false);
        AssoNametxt.setVisible(false);
        DepenIDtxt.setVisible(false);
        DepenNametxt.setVisible(false);
        GeneralIDtxt.setVisible(true);
        GeneralNametxt.setVisible(true);*/
    }//GEN-LAST:event_generalBtnActionPerformed

    private void dependencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dependencyBtnActionPerformed
        /*actorNametxt.setVisible(false);
        UCnametxt.setVisible(false);
        id.setVisible(true);
        actorIDtxt.setVisible(true);
        AssoIDtxt.setVisible(false);
        AssoNametxt.setVisible(false);
        DepenIDtxt.setVisible(true);
        DepenNametxt.setVisible(true);
        GeneralIDtxt.setVisible(false);
        GeneralNametxt.setVisible(false);*/
    }//GEN-LAST:event_dependencyBtnActionPerformed

    private void ScenarioViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScenarioViewMouseClicked
        
    }//GEN-LAST:event_ScenarioViewMouseClicked

    private void ScenarioViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScenarioViewMousePressed
        ScenarioUI ui = new ScenarioUI();
        ui.show();
    }//GEN-LAST:event_ScenarioViewMousePressed

    private void addUsecaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsecaseBtnActionPerformed
        UsecaseUI ui = new UsecaseUI();
        ui.show();
    }//GEN-LAST:event_addUsecaseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UCDevUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UCDevUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UCDevUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UCDevUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UCDevUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssoIDtxt;
    private javax.swing.JTextField AssoNametxt;
    private javax.swing.JTextField DepenIDtxt;
    private javax.swing.JTextField DepenNametxt;
    private javax.swing.JLabel Description;
    private javax.swing.JTextField Descriptiontxt;
    private javax.swing.JLabel Diagram;
    private javax.swing.JTextField GeneralIDtxt;
    private javax.swing.JTextField GeneralNametxt;
    private javax.swing.JMenuItem ScenarioView;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JTextField UCnametxt;
    private javax.swing.JMenu View;
    private javax.swing.JButton actorBtn;
    private javax.swing.JTextField actorIDtxt;
    private javax.swing.JTextField actorNametxt;
    private javax.swing.JButton addActorBtn;
    private javax.swing.JButton addUsecaseBtn;
    private javax.swing.JButton associationBtn;
    private javax.swing.JButton dependencyBtn;
    private javax.swing.JButton generalBtn;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel sterio;
    private javax.swing.JComboBox<String> sterioComboBox;
    private javax.swing.JButton systemBtn;
    private javax.swing.JButton usecaseBtn;
    private javax.swing.JTextField usecaseIDtxt;
    // End of variables declaration//GEN-END:variables
}
